import cx_Oracle
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base


JOIN_EXTERNAL_LIBRARIES = True
ORACLE_DLL = 'oracle_dll'
DB = ...
LIB = ...
USER = ...
PASS = ...
HOST = ...
PORT = ...
DBNAME = ...

if JOIN_EXTERNAL_LIBRARIES:
    cx_Oracle.init_oracle_client(ORACLE_DLL)
dsn = cx_Oracle.makedsn(HOST, PORT, service_name=DBNAME)
connection_string = f'{DB}+{LIB}://{USER}:{PASS}@{dsn}'
engine = create_engine(connection_string, max_identifier_length=128, pool_pre_ping=True, pool_size=20, max_overflow=0)
session_maker = sessionmaker(autocommit=False, autoflush=False, bind=engine, expire_on_commit=False)
Base = declarative_base()
